Add failure cases to execution
dusk-network/piecrust pull request #101
Opened 2022-10-17 11:03 UTC by krl

2022-10-18 07:37 UTC, miloszm requested changes

2022-10-18 07:37 UTC, miloszm commented on vmx/tests/fallible.rs
> +
Is this file empty?

2022-11-08 08:38 UTC, miloszm commented on piecrust-uplink/src/state.rs
> +        // Neccesary to avoid ruling out potential memory changes from recursive
nitpick: spelling error in 'necessary'

2022-11-08 08:39 UTC, miloszm approved these changes
LGTM, one nitpick

2022-11-08 10:47 UTC, ureeves approved these changes
LGTM

2022-11-08 15:39 UTC, krl commented on piecrust-uplink/src/state.rs
> +        // Neccesary to avoid ruling out potential memory changes from recursive
fixed

2022-11-08 15:41 UTC, merged