Added module caching
dusk-network/piecrust pull request #164
Opened 2023-03-02 09:56 UTC by miloszm

Added module caching to avoid compilation on every query/transaction

2023-03-02 10:08 UTC, ureeves requested changes
I don't think we should memoize calls to the compilation of each module. Instead, we should compile the bytecode on deployment, and store the result on disk such that it can be reloaded at any point without having to recompile it.

See the documentation of a [`wasmer::Module`](https://docs.rs/wasmer/latest/wasmer/struct.Module.html#method.serialize) for details on how this would work.

To be clear, I don't think this is wrong, just that there is a much cleaner way of achieving this - even without having to re-compile every cold reboot. Also, no new crates will be necessary.

2023-03-03 20:34 UTC, ureeves reviewed
Found the issue. Explanation in the comments. 

Also, why not just create a new file in the bytecode directory in each commit, representing the compiled bytecode?

Suggestion: Given a module named `module_1`:

```text
commit_dir/
    bytecode/
        module_1
        module_1.a # this being the compiled version
```

This would of course also need to be linked to in commits also using this

2023-03-03 20:34 UTC, ureeves commented on piecrust/src/session/call_stack.rs
> -                };
If an instance is never removed from the map and dropped, then the linear memory `mmap` it is holding is never reloaded from disk - this is why the crossover test is failing

2023-03-03 20:34 UTC, ureeves commented on piecrust/src/error.rs
> +
Is an `io::Error` always a persistence error?

2023-03-09 08:57 UTC, miloszm commented
Regarding the above proposal of placement for compiled files, this is fine but it will lead to proliferation of links, as every compiled file will need to be multiply linked. Since this information is read only, wouldn't it be simpler to have a central location for it?

2023-03-14 09:52 UTC, ureeves commented
> Regarding the above proposal of placement for compiled files, this is fine but it will lead to proliferation of links, as every compiled file will need to be multiply linked. Since this information is read only, wouldn't it be simpler to have a central location for it? Yet I understand the desire of every commit to be fully standalone and independent.

This is true, but it's exactly the same issue as already exists, just that the number of files is increased by one. They would be of the exact same nature and behavior as the bytecode itself.

2023-03-14 10:17 UTC, miloszm commented
I have no problem with the above remark, issue is of different nature. If we want to use `serialize_to_file` method of Wasmer module, at the time this method is called, we don't have a commit yet, so basically at this time we don't have a path for the file. This leads to solutions based on `serialize` only, then we need to keep this buffer somewhere and pass it to commit routine as only at commit we know that path. I am not sure this is worth the complication but we can discuss.

2023-03-14 10:24 UTC, miloszm commented
One more explanatory remark - problem is that before we commit we do not know the path, we only know the path of previous commit or none, if this is a genesis session. With bytecode and module memory this is resolved so that we keep them in memory until the time of commit. With compiled object code this can also be done, but it is not ideal as it complicates the overall design and makes it impossible to use `serialize_to_file` method of Wasmer.

2023-03-17 13:41 UTC, miloszm commented
Changes making compilation-at-deploy-time and object code being stored along with the byte code (as per Ed's comment above), i.e., within the commit-related persistence infrastructure (constituting an object code caching mechanism) are implemented and ready to be reviewed. Given module needs to be compiled only once. Each commit will contain a hard link to object code resulting from compilation, and object code can be loaded (instantiated) on demand if needed, but not more often than once per session.

2023-03-17 14:36 UTC, ureeves commented on piecrust/src/store/session.rs
> +            base_commit.modules.contains_key(&module_id)
```suggestion
        } else if let Some((_, base_commit)) = &self.base {
            base_commit.modules.contains_key(&module_id)
```

2023-03-17 14:37 UTC, ureeves commented on piecrust/src/store.rs
> +const OBJECTCODE_POSTFIX: &str = ".a";
```suggestion
const OBJECTCODE_EXTENSION: &str = ".a";
```

2023-03-17 14:39 UTC, ureeves commented on piecrust/src/store/session.rs
> +                            objectcode_name.push_str(OBJECTCODE_POSTFIX);
Try to use `Path::with_extension`

2023-03-17 15:11 UTC, merged