Module Constructor
dusk-network/piecrust pull request #168
Opened 2023-03-08 15:02 UTC by miloszm

Implements module constructor with dedicated test contract and test,
also renames host_data to meta_data and makes meta_data members optional.

Implements issue #93

2023-03-14 10:07 UTC, ureeves requested changes
I'm not sure we should return `None` on *any* piece of metadata. If metadata is unset and the contract requests it, I think it should panic - much like de-referencing a pointer to memory not owned by a program.

2023-03-14 10:07 UTC, ureeves commented on modules/constructor/src/lib.rs
> +}
I'm unsure about the `init` name. Proposals would be:

- `new`
- `ctor`
- `init`

2023-03-14 11:02 UTC, miloszm commented
Optionality of metadata was requested by Matteo, I noted down his request in issue #93. As far as name concerned, I am open for discussion.

2023-03-21 09:49 UTC, ureeves requested changes
Overall the implementation is good, but there's several issues I can see. I don't think we need to broaden the exposed API for this -  meaning we should avoid the proliferation of `deploy-*` calls, exporting constants (only used in tests).

There's also the problem of call history. With this implementation, an `init` call cannot be replayed, since we forget the data used in the call.

2023-03-21 09:49 UTC, ureeves commented on piecrust/src/lib.rs
> +pub use session::{Session, CONTRACT_INIT_METHOD};
What is the reasoning for exporting this?

2023-03-21 09:49 UTC, ureeves commented on piecrust/src/session.rs
> +    pub fn deploy_and_init<Arg>(
It's probably better to modify the existing function `deploy` and `deploy_with_id` to take an `Option<Arg>`. Doing it this way implies the caller should somehow "know" that the given bytecode has a constructor,, which they are clearly not in a position to do.

2023-03-21 09:49 UTC, ureeves commented on piecrust/src/session.rs
> +    pub fn deploy_with_id_and_init<Arg>(
Ditto here

2023-03-21 15:07 UTC, ureeves requested changes
I think the serialization logic can be further simplified. Below a suggestion on how to do that, following the same pattern as what `query` and `transact` do.

2023-03-21 15:07 UTC, ureeves commented on piecrust/tests/box.rs
> +    let id = session.deploy(module_bytecode!("box"), None::<()>)?;
I didn't know one could do this on the enum's variant. Interesting!

2023-03-22 10:44 UTC, ureeves approved these changes
LGTM

2023-03-22 10:45 UTC, merged